on:
#   push:
  issue_comment:
    types:
      [created]
  
name: "Issue name change"
jobs:
  build:
    if: ${{github.event.comment.body == 'Build website'}}
    name: Change issue title
    runs-on: ubuntu-latest
    steps:
      - id: label 
        run: echo ${{github.event.issue}}
#       - id: tolowerCase
#         uses: ASzc/change-string-case-action@v5
#         with:
#           string: ${{github.event.comment.body}}
#       - id: print 
#         run: echo ${{steps.tolowerCase.outputs.lowercase}}
